### ISSUE TITLE
❓️QUESTION - Does this action support passing all the potential options to the pushover API?

### ISSUE THREAD

**Issue by tallguyjenks** [umahmood/pushover-actions#6]
are all of these supported in the `with` section of the action?

![image](https://github.com/user-attachments/assets/cce0f7bb-cf58-4e38-9478-cfe4f8448f15)

**Comment by umahmood** [comment]
Hello @tallguyjenks , 

No, not all those are supported. Only the following options are supported in the `with` section:

- message
- title
- url
- url_title
- device
- priority 
- sound	

Thanks.
